import { lazy, Suspense, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowRight, ArrowDown, ArrowLeft, Github, Mail, Copy, Check, Download, X, Menu, Play, Pause, RotateCcw } from 'lucide-react';
import '@fontsource/dm-sans/400.css';
import '@fontsource/dm-sans/500.css';
import '@fontsource/dm-sans/600.css';
import '@fontsource/instrument-serif/400.css';
import '@fontsource/instrument-serif/400-italic.css';
import './style.css';
import orbit from './orbit.png';
import jmac from './jmac.png';
import portrait from './portrait.jpg';
import resume from './Achilles-Asuncion-Resume.pdf';

const Gallery = lazy(() => import('./Gallery'));
const email = 'achillespasuncion@gmail.com';
const projects = [
  { name:'ACHILLES / ORBIT', short:'ORBIT', category:'Creative web experience', url:'https://achilles-orbit.vercel.app', image:orbit, year:'2026', description:'An exploration of creative technology through an interactive orbital sculpture, spatial interfaces, and a story that unfolds as you scroll.', tags:['Interactive 3D','Creative development','Motion'], detail:'The experience brings an inspectable 3D sculpture into a chapter-based website. Layer selection, spatial motion, and an optional sound control let visitors explore beyond a static page.', focus:'Bringing movement, depth, and interface design into one coherent experience.', note:'A creative studio concept and web experiment. The studio commissions described in the demo are concept content.' },
  { name:'JMAC Enterprise', short:'JMAC', category:'Enterprise web platform', url:'https://jmac-enterprise.vercel.app', image:jmac, year:'2026', description:'A unified interface for people and business operations, connecting human resources, point of sale, finance, and employee self-service.', tags:['Product interface','Responsive web','Enterprise workflows'], detail:'The public experience introduces four connected workspaces and provides clear paths for careers, application tracking, and employee access. Its interface prioritizes structure and clarity across a complex product.', focus:'Organizing connected workflows into a clear, approachable web experience.', note:'Explore the public site. Employee workspaces require authorized access.' }
];

function useReducedMotion() {
  const [reduced,setReduced]=useState(()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches);
  useEffect(()=>{const q=window.matchMedia('(prefers-reduced-motion: reduce)'); const change=()=>setReduced(q.matches);q.addEventListener('change',change);return()=>q.removeEventListener('change',change);},[]);
  return reduced;
}

function Intro({ reduced }: { reduced:boolean }) {
  const [open,setOpen]=useState(()=>!reduced && !sessionStorage.getItem('aa-intro'));
  useEffect(()=>{ if(!open) return; const end=()=>{setOpen(false);sessionStorage.setItem('aa-intro','seen');}; const timer=setTimeout(end,2100); const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')end();}; window.addEventListener('keydown',escape); return()=>{clearTimeout(timer);window.removeEventListener('keydown',escape);};},[open]);
  if(!open || reduced) return null;
  return <div className="intro"><span className="intro-caption">A portfolio by Achilles Asuncion</span><div className="intro-word"><span>Ideas.</span><i>Into motion.</i></div><div className="intro-bottom"><span>Design. Develop. Discover.</span><button onClick={()=>{setOpen(false);sessionStorage.setItem('aa-intro','seen');}}>Skip intro <ArrowRight size={16}/></button></div><div className="intro-line"/></div>;
}

function Playground({reduced}:{reduced:boolean}) {
  const [mode,setMode]=useState<'motion'|'terminal'>('motion');
  const [speed,setSpeed]=useState(5);
  const [paused,setPaused]=useState(reduced);
  const [command,setCommand]=useState('');
  const [history,setHistory]=useState(['Hello, curious human. Type help to explore.']);
  const output=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(reduced)setPaused(true);},[reduced]);
  useEffect(()=>{if(output.current)output.current.scrollTop=output.current.scrollHeight;},[history]);
  function submit(e:React.FormEvent){e.preventDefault();const input=command.trim().toLowerCase();if(!input)return;const answers:Record<string,string>={help:'Try: about · skills · projects · contact · clear',about:'Achilles Asuncion / fnvaccky. BSIT student, frontend developer, and a creative at heart.',skills:'HTML · CSS · JavaScript · React. Also exploring backend development and databases.',projects:'ORBIT — creative 3D experience. JMAC — enterprise web platform. Explore both in Selected work.',contact:email};setHistory(h=>input==='clear'?[]:[...h.slice(-8),`> ${input}`,answers[input]||`Command "${input}" not found. Type help for a few ideas.`]);setCommand('');}
  return <section id="playground" className="playground section-wrap"><div className="playground-copy"><h2>A little room<br/>to <em>play.</em></h2><p>Good interfaces invite a little curiosity. Here’s a small corner to turn a dial, try a command, and see what happens.</p><span className="quiet-label">Built for the joy of figuring things out.</span></div><div className="lab"><div className="lab-header"><div className="lab-tabs" role="tablist" aria-label="Interactive experiments"><button role="tab" aria-selected={mode==='motion'} aria-controls="experiment" onClick={()=>setMode('motion')}>Motion study</button><button role="tab" aria-selected={mode==='terminal'} aria-controls="experiment" onClick={()=>setMode('terminal')}>Terminal</button></div><span className="lab-status"><span/> Interactive</span></div><div id="experiment" role="tabpanel" aria-label={mode==='motion'?'Motion study':'Terminal'}>{mode==='motion'?<><div className="motion-stage"><div className={`bloom ${paused?'paused':''}`} style={{animationDuration:`${22-speed*1.7}s`}}>{Array.from({length:8},(_,i)=><span key={i} style={{transform:`rotate(${i*45}deg) translateY(-44px)`}}/>)}</div><span className="motion-caption">A study in repetition & rhythm</span></div><div className="lab-controls"><label htmlFor="motion-speed">Motion speed</label><input id="motion-speed" type="range" min="1" max="10" value={speed} onChange={e=>setSpeed(Number(e.target.value))}/><button className="icon-button" aria-label={paused?'Play motion study':'Pause motion study'} onClick={()=>setPaused(!paused)}>{paused?<Play size={16}/>:<Pause size={16}/>}</button><button className="icon-button" aria-label="Reset motion study" onClick={()=>{setSpeed(5);setPaused(reduced);}}><RotateCcw size={16}/></button></div></>:<div className="terminal"><div className="terminal-output" ref={output} role="log" aria-label="Terminal responses">{history.map((line,i)=><p key={i}>{line}</p>)}</div><form onSubmit={submit}><label htmlFor="terminal-command">fnvaccky ~ $</label><input id="terminal-command" autoComplete="off" spellCheck={false} placeholder="type help" value={command} onChange={e=>setCommand(e.target.value)}/><button className="icon-button" aria-label="Run command"><ArrowRight size={18}/></button></form></div>}</div></div></section>;
}

function App(){
 const reduced=useReducedMotion();const [galleryPaused,setGalleryPaused]=useState(false);const [active,setActive]=useState(0);const [menu,setMenu]=useState(false);const [copied,setCopied]=useState(false); const [copyError,setCopyError]=useState(false);
 useEffect(()=>{const reveal=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');reveal.unobserve(entry.target);}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>reveal.observe(el));return()=>reveal.disconnect();},[]);
 const copy=async()=>{try{await navigator.clipboard.writeText(email);setCopied(true);setCopyError(false);setTimeout(()=>setCopied(false),2400);}catch{setCopyError(true);}};
 return <><Intro reduced={reduced}/><a className="skip-link" href="#main">Skip to content</a><header className="header"><a className="brand" href="#home" aria-label="Achilles Asuncion home"><span className="brand-mark">a<span>a</span></span><span>Achilles Asuncion<span className="brand-alias"> / fnvaccky</span></span></a><button className="menu-toggle icon-button" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} aria-controls="navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav id="navigation" className={menu?'nav open':'nav'} aria-label="Main navigation"><a href="#work" onClick={()=>setMenu(false)}>Work</a><a href="#about" onClick={()=>setMenu(false)}>About</a><a href="#playground" onClick={()=>setMenu(false)}>Playground</a><a href="#contact" className="nav-contact" onClick={()=>setMenu(false)}>Let’s talk <ArrowUpRight size={15}/></a></nav></header>
 <main id="main"><section id="home" className="hero"><div className="hero-copy"><h1>Thoughtfully built.<br/><em>Made to move.</em></h1><p>I’m Achilles, a frontend developer with a creative eye. I turn ideas into web experiences that feel as good as they look.</p><a className="button primary" href="#work">View selected work <ArrowDown size={17}/></a><div className="availability"><span className="status-dot"/> Open to internships & frontend opportunities</div></div><div className="hero-gallery" aria-label="Interactive project gallery"><Suspense fallback={<img className="scene-loading" src={orbit} alt="ORBIT project preview"/>}><Gallery active={active} reduced={reduced} paused={galleryPaused} onSelect={setActive}/></Suspense><div className="gallery-controls"><div className="gallery-title" aria-live="polite"><span>{String(active+1).padStart(2,'0')} / 02</span><strong>{projects[active].short}</strong><span className="gallery-hint">Drag to explore</span></div><div className="gallery-arrows"><button className="icon-button" aria-label={galleryPaused?"Resume gallery motion":"Pause gallery motion"} onClick={()=>setGalleryPaused(!galleryPaused)}>{galleryPaused?<Play size={16}/>:<Pause size={16}/>}</button><button className="icon-button" aria-label="Previous project" onClick={()=>setActive(1-active)}><ArrowLeft size={19}/></button><button className="icon-button" aria-label="Next project" onClick={()=>setActive(1-active)}><ArrowRight size={19}/></button></div></div><a className="gallery-explore" href={`#project-${active}`}>Explore {projects[active].short} <ArrowUpRight size={15}/></a></div><div className="hero-bottom"><span>Creative by nature. Developer by choice.</span><span>Based in the Philippines <span className="tiny-circle"/></span></div></section>
 <section id="work" className="work section-wrap"><div className="section-heading reveal"><h2>Selected <em>work.</em></h2><p>From expressive experiments to everyday tools.<br/>A few things I’ve been building.</p></div>{projects.map((project,i)=><article key={project.short} className={`project reveal project-${i}`} id={`project-${i}`}><a className="project-image" href={project.url} target="_blank" rel="noreferrer" aria-label={`Visit ${project.name} live site`}><div className="image-mat"><img src={project.image} alt={`${project.name} homepage`} width="1274" height="716" loading="lazy"/></div><span className="visit-project">Visit live site <ArrowUpRight size={18}/></span></a><div className="project-information"><div className="project-name"><span>{project.category}</span><h3>{project.name}</h3></div><div className="project-description"><p>{project.description}</p><div className="project-tags">{project.tags.map(tag=><span key={tag}>{tag}</span>)}</div><details><summary>Inside the project <span className="details-plus" aria-hidden="true">+</span></summary><div className="project-detail"><p>{project.detail}</p><h4>Interface focus</h4><p>{project.focus}</p><p className="project-note">{project.note}</p><a href={project.url} target="_blank" rel="noreferrer">Explore the live experience <ArrowUpRight size={15}/></a></div></details></div></div></article>)}</section>
 <section id="about" className="about section-wrap"><div className="about-portrait reveal"><div className="portrait-paper"><img src={portrait} alt="Achilles Asuncion" width="616" height="616" loading="lazy"/></div><span>Achilles Asuncion<span>Also known as fnvaccky</span></span><span className="portrait-scribble">Always a work in progress.</span></div><div className="about-copy reveal"><h2>A creative mind.<br/><em>A builder’s instinct.</em></h2><p className="about-lead">I’ve always liked making things look and feel right. Frontend development gave that curiosity a place to grow.</p><p>I’m studying BS Information Technology at the National College of Science and Technology. I enjoy the space where thoughtful design meets working code—building responsive interfaces, exploring interactions, and learning some backend along the way.</p><p>I’m still learning, and that’s a part of the work I love. I share what I discover and help fellow coders whenever I can.</p><div className="education"><span>Currently</span><strong>BS Information Technology</strong><span>National College of Science and Technology · 2024–present</span></div><a className="text-link" href={resume} download="Achilles-Asuncion-Resume.pdf">Download my résumé <Download size={17}/></a></div></section>
 <section className="toolkit section-wrap"><div className="section-heading reveal"><h2>My growing <em>toolkit.</em></h2><p>Tools are the starting point.<br/>What we make with them is the interesting part.</p></div><div className="skill-rows reveal"><div><h3>Frontend & interfaces</h3><p>HTML · CSS · JavaScript · React · Tailwind CSS · Vite</p></div><div><h3>Beyond the browser</h3><p>Node.js · Python · PHP · MySQL · Supabase</p></div><div><h3>Design & workflow</h3><p>Figma · Git · GitHub · VS Code · Vercel</p></div><div><h3>Exploring next</h3><p>TypeScript · Three.js · Vue · Docker</p></div></div></section>
 <Playground reduced={reduced}/>
 <section id="contact" className="contact section-wrap"><div className="contact-top"><div className="availability"><span className="status-dot"/> Let’s make something good.</div><span>Internships / Frontend roles / Freelance</span></div><h2>Have something<br/><em>in mind?</em><a href={`mailto:${email}`} className="contact-arrow" aria-label="Email Achilles"><ArrowUpRight strokeWidth={1} /></a></h2><div className="contact-bottom"><div><a className="email-link" href={`mailto:${email}`}>{email}</a><button className="copy-button" onClick={copy} aria-label="Copy email address">{copied?<Check size={16}/>:<Copy size={16}/>}<span aria-live="polite">{copied?'Copied':'Copy'}</span></button>{copyError&&<p role="status">Please select the email above to copy it.</p>}</div><p>I’d love to hear about your team,<br/>your idea, or what you’re building.</p></div><div className="socials"><a href="https://github.com/fnvaccky" target="_blank" rel="noreferrer"><Github size={16}/> GitHub <ArrowUpRight size={14}/></a><a href="https://www.instagram.com/fnvaccky" target="_blank" rel="noreferrer">Instagram <ArrowUpRight size={14}/></a><a href="https://www.facebook.com/Achilles" target="_blank" rel="noreferrer">Facebook <ArrowUpRight size={14}/></a><a href="https://discord.gg/kPQkjqaB" target="_blank" rel="noreferrer">Discord <ArrowUpRight size={14}/></a><a href={`mailto:${email}`}><Mail size={16}/> Email <ArrowUpRight size={14}/></a></div></section>
 </main><footer><span>© {new Date().getFullYear()} Achilles Asuncion</span><span>Made with curiosity & care.</span><a href="#home">Back to top <ArrowUpRight size={14}/></a></footer></>;
}
createRoot(document.getElementById('root')!).render(<App/>);
